# FUJITSU LIMITED:2014-10-27 H1515009 add start
#
# Makefile for the input core drivers.
#

# Each configuration option enables a list of files.

obj-y				+= mmcdl.o


# FUJITSU LIMITED:2014-10-27 H1515009 add end
