#===============================================================================
# COPYRIGHT(C) FUJITSU LIMITED 2013 - 2014
#===============================================================================
# FUJITSU LIMITED:2014-10-23 H1510036 add start

#
# Makefile for the input core drivers.
#

# Each configuration option enables a list of files.

obj-y		+= nonvolatile.o

# FUJITSU LIMITED:2014-10-23 H1510036 add end
