#
# Makefile for fujitsu devices that really don't fit anywhere else.
#

# FUJITSU LIMITED:2014-10-27 H1515008 add start
obj-y		+= fjsmem/
# FUJITSU LIMITED:2014-10-27 H1515008 add end
# FUJITSU LIMITED:2014-10-31 H1510031 add start
obj-y		+= fjwdog/
# FUJITSU LIMITED:2014-10-31 H1510031 add end
# FUJITSU LIMITED:2016-01-20 ADD-S
#hce
obj-y		+= walkmotion/
# FUJITSU LIMITED:2016-01-20 ADD-E
# FUJITSU LIMITED:2016-01-28 ADD-S
obj-y		+= compass/
# FUJITSU LIMITED:2016-01-28 ADD-E
# FUJITSU:2016-01-20 add-s DTV
obj-y		+= ftdtv_drv/
obj-y		+= libtuner_drv/
# FUJITSU:2016-01-20 add-e DTV
